options:

# Package information
  extra-source:
    type: string
    default: ''
    description: apt repository to fetch nuage from
  extra-key:
    type: string
    default: ''
    description: repository key

## Neutron section
  nuage-service-plugins:
    type: string
    default: 'NuagePortAttributes,NuageAPI,NuageL3'
    description: Nuage Service Plugins 

## ML2 Section
  overlay-network-types:
    default: vxlan
    type: string
    description: |
      Overlay network types to use, valid options include:
      .
      vxlan
      .
      Multiple types can be provided in the future - field is comma seperated

  tenant-network-types:
    default: vxlan
    type: string
    description: |
      Overlay network types to use, valid options include:
      .
      vxlan
      .
      Multiple types can be provided in the future - field is comma seperated

  vlan-ranges:
    type: string
    default: ''
    description: |
      Space-delimited list of Neutron network-provider & vlan-id-ranges using
      the following format "<provider>:<start>:<end> ..." like "default:1000:2000".

  mechanism-drivers:
    default: nuage
    type: string
    description: |
      Nuage mechanism drivers you want to enable
      It is 'nuage,nuage_sriov,sriovnicswitch' when you enable sriov

  extension-drivers:
    default: 'nuage_subnet,nuage_port,port_security'
    type: string
    description: |
      Nuage extentions mechanism drivers you want to enable

  vni-ranges:
    type: string
    default: '1001:2000'
    description: |
      Space-delimited list of Neutron network-provider & vxlan-vni-ranges using
      the following format "<start>:<end> ..." like "1000:2000".

  vxlan-group:
    default: '224.0.0.1'
    type: string
    description: |
      Nuage default vxlan group 

#Nuage Section
# [ restproxy ]
  server:
    type: string
    default: 'vsd.example.com:8443'
    description: "IP address and port of Nuage's VSD server or cluster" 
  serverauth:
    type: string
    default: "csproot:csproot"
    description: "Username and password for authentication"
  serverssl:
    type: boolean
    default: True
    description: "Boolean for SSL connection with VSD server"
  verify-cert:
    type: boolean
    default: False 
    description: |
      Either a boolean (True or False), indicating whether
      we verify the VSD's certificate, or a string which is
      the local path of the VSD's PEM file or CA_BUNDLE file
      to be verified
  server-timeout:
    type: int
    default: 30
    description: "VSD server invocation timeout" 
  server-max-retries:
    type: int
    default: 5
    description: "VSD server invocation timeout" 
  base-uri:
    type: string
    default: "/nuage/api/v5_0"
    description: "Nuage provided base uri to reach out to VSD" 
  organization:
    type: string
    default: csp
    description: |
      Organization name in which VSD will orchestrate
      network resources using openstack
  auth-resource:
    type: string
    default: "/me"
    description: "Nuage provided uri for initial authorization to access VSD"
  default-net-partition-name:
    type: string
    default: juju-enterprise
    description: |
      Default Network partition in which VSD will 
      orchestrate network resources using openstack 
  nuage-pat:
    type: string
    default: "default_disabled"
    description: "" 
  nuage-underlay-default:
    type: string
    default: "off"
    description: "" 
  nuage-fip-underlay:
    type: boolean
    default: False 
    description: "" 
  cms-id:
    type: string
    default:
    description: |
      CMS ID is used as an authentication token from VSD to CMS.
      This value is being generated via nuage scripts and can be set pre/post
      deployment.
  nuage-uplink:
    type: string
    default: "" 
    description: 

# [plugin]
  experimental-features:
    type: string
    default: "" 
    description: 
  enable-debug:
    type: string
    default: "" 
    description: "" 
