options:

# Package information
  install_sources:
    type: string
    default: ''
    description: apt repository to fetch nuage from
  install_keys:
    type: string
    default: ''
    description: repository key

## Neutron section
  nuage-service-plugins:
    type: string
    default: 'NuagePortAttributes,NuageAPI,NuageL3'
    description: Nuage Service Plugins 

## ML2 Section
  overlay-network-types:
    default: vxlan
    type: string
    description: |
      Overlay network types to use, valid options include:
      .
      vxlan
      .
      Multiple types can be provided in the future - field is comma seperated

  tenant-network-types:
    default: vxlan
    type: string
    description: |
      Overlay network types to use, valid options include:
      .
      vxlan
      .
      Multiple types can be provided in the future - field is comma seperated

  vlan-ranges:
    type: string
    default: ''
    description: |
      Space-delimited list of Neutron network-provider & vlan-id-ranges using
      the following format "<provider>:<start>:<end> ..." like "default:1000:2000".

  mechanism-drivers:
    default: nuage
    type: string
    description: |
      Nuage mechanism drivers you want to enable
      It is 'nuage,nuage_sriov,sriovnicswitch' when you enable sriov

  extension-drivers:
    default: 'nuage_subnet,nuage_port,port_security'
    type: string
    description: |
      Nuage extentions mechanism drivers you want to enable

  vni-ranges:
    type: string
    default: '1001:2000'
    description: |
      Space-delimited list of Neutron network-provider & vxlan-vni-ranges using
      the following format "<start>:<end> ..." like "1000:2000".

  vxlan-group:
    default: '224.0.0.1'
    type: string
    description: |
      Nuage default vxlan group 

#Nuage Section

  vsd-cms-id:
    type: string
    default:
    description: |
      CMS ID is used as an authentication token from VSD to CMS.
      This value is being generated via nuage scripts and can be set pre/post
      deployment.
  vsd-server:
    type: string
    default:
    description: Nuage VSD Server
  vsd-auth:
    type: string
    default: "csproot:csproot"
    description: Username Password to connect to Nuage VSD Server
  vsd-organization:
    type: string
    default: csp
    description: Name of the organization in Nuage VSD
  vsd-auth-ssl:
    type: boolean
    default: True
    description: SSL authentication of the Nuage VSD Server
  vsd-base-uri:
    type: string
    default: "/nuage/api/v5_0"
    description: Nuage VSD API endpoint URI
  vsd-auth-resource:
    type: string
    default: "/me"
    description: Nuage VSD authentication resource
  vsd-netpart-name:
    type: string
    default: juju-enterprise
    description: Name of the Organization or Enterprise to create in Nuage VSD
